### ISSUE TITLE
Emit helpful PoX events

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2554]
We should emit PoX Stacking events in the 2.1 contract.  Let's gather a list of them here.

**Comment by kantai** [comment]
From @zone117x:

> See issue blockstack/stacks-blockchain-api#465
> 
> There's a desire for the node.js API to be able to enumerate and perform other types of queries against PoX delegation state. In order to do this, the stacks-node needs to emit all mutations to the delegation state maps in order for the API to track.
> 
> In this case, I think we need either a new event, or new event data added to an existing event.
> 
> In the future, built-in contracts should attempt to take more advantage of the structured contract-log (i.e. print function) to expose these various kinds of state changes.

**Comment by jcnelson** [comment]
Strictly speaking, we do not need to update the `.pox` (or `.pox-2`) contract for this -- we can just add special cases in the Clarity VM if need be.  Going to untag this from 2.1 for now.

**Comment by markmhx** [comment]
This is resolved now, correct? Can we close?

**Comment by zone117x** [comment]
Yeah, I think there's at least this issue remaining: https://github.com/stacks-network/stacks-blockchain/issues/3529
